### ISSUE TITLE
Token confusion

### ISSUE THREAD

**Issue by nifl** [carrot/sprout-static-cms#7]
Can you explain the difference between an access token and a management token? I’m trying to set up an application that asks for each of these. Currently I have two API access tokens (Production & Preview) as well as an OAuth token. Are any of these three a management token? They’re all labeled as access tokens.

**Comment by kylemac** [comment]
@nifl try it with just the `access_token`. i don't think that the management token is supported any more.

**Comment by nifl** [comment]
It looks like the URI needs to be updated from `api.contentful.com:443` to `cdn.contentful.com`

Consider the following two requests - the first coming from `sprout`

```
GET https://api.contentful.com:443/spaces/78zejdkeep0n access_token=a070fc38c0a22fcf9d211c4fd8crap45870b0e297a2c1eb24ca5eef8b8484ab2 The access token you sent could not be found or is invalid. {"sys":{"type":"Error","id":"AccessTokenInvalid"},"requestId":"9e1-614553853","message":"The access token you sent could not be found or is invalid."}
```

where directly calling, 

```
GET https://api.contentful.com:443/spaces/78zejdkeep0n access_token=a070fc38c0a22fcf9d211c4fd8crap45870b0e297a2c1eb24ca5eef8b8484ab2` 
```

returns the expected request.

**Comment by AndrewCull** [comment]
Any idea on where to change the URI in this project?  Contentful.js (NPM Module) is pointing to cdn.contentful.com, curl works fine so the api is working and token is correct. I keep getting "The access token you sent could not be found or is invalid." error when running 'roots watch'.

**Comment by kylemac** [comment]
@AndrewCull you're right the URL does need to be changed. right now this sprout template uses `roots-contentful` `0.0.7`. The newest version on npm is `0.0.9` (just pushed an update). if you upgrade your project to 0.0.9 -- you should see this error is fixed. please let me know if that does the trick. cc @nifl

**Comment by justrjlewis** [comment]
@kylemac I ran npm update on the package, but I'm still getting the error `AccessTokenInvalid: GET https://api.contentful.com:443/spaces/...`when I try to generate the models.

**Comment by bnchdrff** [comment]
I generated a content management oauth token using contentful's client in their docs: https://www.contentful.com/developers/docs/references/authentication/#getting-an-oauth-token

works great.
